<?xml version="1.0"?>
<robot name="erod" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find erod_description)/urdf/properties.xacro" />
    <xacro:include filename="$(find erod_description)/urdf/materials.xacro" />
    <xacro:include filename="$(find erod_description)/urdf/erod.gazebo" />
    <!-- xacro:include filename="$(find erod_description)/urdf/laser.xacro" / -->
    <!-- xacro:include filename="$(find erod_description)/urdf/laser2.xacro" / -->
    <!-- xacro:include filename="$(find erod_description)/urdf/camera.xacro" / -->

    <!-- eRod-Model -->

		<link name="footprint"/>

    <joint name="base_link" type="fixed">
			<parent link="footprint" />
			<child link="base_link" />
			<origin xyz="0 0 0.6" rpy="0 0 0" />
		</joint>

    <!-- Chassis -->
    <link name="base_link">
      <inertial>
        <mass value="${carMass}" />
        <origin xyz="0 0 0" />
        <inertia  ixx="${carIxx}" ixy="0.0"  ixz="0.0"  iyy="${carIyy}"  iyz="0.0"  izz="${carIzz}" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="${0} 0 0" />
        <!-- origin xyz="1 0 0" rpy="${M_PI/2} 0 0" / -->
        <geometry>
        <box size="${carLength} ${carWidth} ${carHeight}" />
        <!-- mesh filename="package://meshes/meshes/eRod.dae"/ -->
        </geometry>
        <material name="Blue"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${carLength} ${carWidth} ${carHeight}" />
        </geometry>
      </collision>
    </link>

    <!-- A link which is needed for the P3D Sensor which is as in reality -->
    <joint name="perfect_state_joint" type="fixed">
      <parent link="base_link" />
      <child link="perfect_state_link" />
      <origin xyz="${-wheelBase/2} 0 ${-carHeight/2-groundClearance+wheelRadius}" rpy="0 0 0" />
    </joint>
    <link name="perfect_state_link">
    </link>

    <!-- Front link of Ackermann -->
    <joint name="front_joint" type="fixed">
    	<parent link="base_link"/>
    	<child link="front_link"/>
    	<origin xyz="${wheelBase/2} 0.0 ${-carHeight/2-groundClearance+wheelRadius}"/>
    </joint>

    <link name="front_link">
      <inertial>
        <mass value="${dummyM}"/>
        <origin xyz="0 0 0" />
        <inertia  ixx="${dummyI}" ixy="0.0"  ixz="0.0"  iyy="${dummyI}"  iyz="0.0"  izz="${dummyI}" />
      </inertial>
      <visual>
        <geometry>
          <box size="${carLength*0.05} ${carWidth} ${carHeight*0.05}" />
        </geometry>
      </visual>
      <collision>
        <geometry>
          <box size="${carLength*0.05} ${carWidth} ${carHeight*0.05}" />
        </geometry>
      </collision>
    </link>

    <!-- the left Ackermann bar -->
    <joint name="front_left_bar_joint" type="revolute" >
        <limit lower="${-max_steer}" upper="${max_steer}" effort="100" velocity="10" />
        <axis xyz="0 0 1" />
        <parent link="front_link" />
        <child link="front_left_bar_link" />
        <origin xyz="0.0 ${hingeWidth/2} 0.0" rpy="0 0 0" />
        <dynamics damping="0.7"/>
    </joint>
    <link name="front_left_bar_link">
        <inertial>
            <mass value="${dummyM}" />
            <origin xyz="0 0 0" />
            <inertia  ixx="${dummyI}" ixy="0.0"  ixz="0.0"  iyy="${dummyI}"  iyz="0.0"  izz="${dummyI}" />
        </inertial>
        <visual>
            <origin xyz="${-carWidth*0.1} 0 0" />
            <geometry>
                <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
				<origin xyz="${-carWidth*0.1} 0 0" />
            <geometry>
                <box size="${-carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_left_bar_link">
        <material>Gazebo/Green</material>
    </gazebo>

    <!-- the right Ackermann bar -->
    <joint name="front_right_bar_joint" type="revolute" >
        <limit lower="${-max_steer}" upper="${max_steer}" effort="100" velocity="10" />
        <axis xyz="0 0 1" />
        <parent link="front_link" />
        <child link="front_right_bar_link" />
        <origin xyz="0.0 ${-hingeWidth/2} 0.0" rpy="0 0 0" />
        <dynamics damping="0.7"/>
    </joint>
    <link name="front_right_bar_link">
		<inertial>
				<mass value="${dummyM}" />
				<origin xyz="0 0 0" />
				<inertia  ixx="${dummyI}" ixy="0.0"  ixz="0.0"  iyy="${dummyI}"  iyz="0.0"  izz="${dummyI}" />
		</inertial>
		<visual>
			<origin xyz="${-carWidth*0.1} 0 0" />
			<geometry>
				<box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
			</geometry>
			<material name="Green"/>
		</visual>
		<collision>
		  <origin xyz="${-carWidth*0.1} 0 0" />
			<geometry>
			  <box size="${-carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
			</geometry>
		</collision>
    </link>

	<!-- the front left wheel -->
    <joint name="front_left_wheel_joint" type="continuous" >
        <axis xyz="0 1 0" />
        <parent link="front_left_bar_link" />
        <child link="front_left_wheel_link" />
        <origin xyz="0 ${trackWidth/2-hingeWidth/2} 0" rpy="0 0 0" />
    </joint>

    <link name="front_left_wheel_link">
        <inertial>
            <mass value="${wheelMass}" />
            <origin xyz="0 0 0" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
              <!-- mesh filename="package://meshes/meshes/rad_eRod.dae"/ -->
              <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
        </collision>
    </link>

	<!-- the front right wheel -->
    <joint name="front_right_wheel_joint" type="continuous" >
        <axis xyz="0 -1 0" />
        <parent link="front_right_bar_link" />
        <child link="front_right_wheel_link" />
        <origin xyz="0 ${-(trackWidth/2-hingeWidth/2)} 0" rpy="0 0 0" />
    </joint>
    <link name="front_right_wheel_link">
        <inertial>
            <mass value="${dummyM}" />
            <origin xyz="0 0 0" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${-M_PI/2} 0 0" />
            <geometry>
            <!-- mesh filename="package://meshes/meshes/rad_eRod.dae"/ -->
            <cylinder radius="${wheelRadius}" length="${wheelWidth}" />            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
        </collision>
    </link>

		<!-- the back left wheel -->
    <joint name="back_left_wheel_joint" type="continuous" >
        <axis xyz="0 1 0" />
        <parent link="base_link" />
        <child link="back_left_wheel_link" />
				<origin xyz="${-wheelBase/2} ${trackWidth/2} ${-carHeight/2-groundClearance+wheelRadius}" rpy="0 0 0" />
    </joint>
    <link name="back_left_wheel_link">
        <inertial>
            <mass value="${wheelMass}" />
            <origin xyz="0 0 0" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
            <!-- mesh filename="package://meshes/meshes/rad_eRod.dae"/ -->
            <cylinder radius="${wheelRadius}" length="${wheelWidth}" />            </geometry>
            <material name="Black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
        </collision>
    </link>

	<!-- the back right wheel -->
    <joint name="back_right_wheel_joint" type="continuous" >
        <axis xyz="0 -1 0" />
        <parent link="base_link" />
        <child link="back_right_wheel_link" />
        <origin xyz="${-wheelBase/2} ${-trackWidth/2} ${-carHeight/2-groundClearance+wheelRadius}" rpy="0 0 0" />
    </joint>

    <link name="back_right_wheel_link">
        <inertial>
            <mass value="${wheelMass}" />
            <origin xyz="0 0 0" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${-M_PI/2} 0 0" />
            <geometry>
            <!-- mesh filename="package://meshes/meshes/rad_eRod.dae"/ -->
            <cylinder radius="${wheelRadius}" length="${wheelWidth}" />            </geometry>
            <material name="Black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
        </collision>
    </link>

    <!-- Transmission elements -->

    <transmission name="tran1">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="front_left_bar_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor1">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <transmission name="tran2">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="front_right_bar_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor2">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <transmission name="tran3">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="back_left_wheel_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor3">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>10</mechanicalReduction>
      </actuator>
    </transmission>

    <transmission name="tran4">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="back_right_wheel_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor4">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>10</mechanicalReduction>
      </actuator>
    </transmission>



</robot>
